name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: hashilbasheer/argocd-test
    
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
        
        
    - name: Update deployment YAML
      run: |
        yq e '.spec.template.spec.containers[0].image.tag = "7d862f2" ' deploy/deploy.yaml
        tee -a deploy/deploy.yaml << EOF
        This is text entered via the keyboard or via a script.
        EOF
    
      
      
    - name: Commit changes
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add deploy/deploy.yaml
        git commit -m "Update deployment image tag"
        git push  
