name: Clone Public Repository Workflow

on:
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'hashilbasheer'
          repository: 'argocd-test'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd argocd-test
          ls -la deploy
          
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Patch YAML file with yq
        run: |
          IMAGE_TAG=e7d2610
          yq e ".spec.template.spec.containers[0].image = \" ghcr.io/hashilbasheer/react-poc:e7d2610\"" -i argocd-test/deploy/deploy.yaml    
      - name: Push back to remote repo
        run: |
           git config --global user.email "tester@example.com"
           git config --global user.name "tester"
           cd argocd-test/deploy
           git add .
           git commit -m " testing on "
           git push origin main
           
