name: Patch YAML file
on:
  push:
    branches:
      - main
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clone remote repository
        run: git clone https://github.com/hashilbasheer/argocd-test.git remote
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Patch YAML file with yq
        run: |
          yq e ".spec.template.spec.containers[0].image = \" ghcr.io/hashilbasheer/react-poc:${IMAGE_TAG}\"" -i remote/deploy/deploy.yaml
      - name: Commit changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add deploy/deploy.yaml
          git commit -m "Patch YAML file"
      - name: Push changes
        run: |
          git push https://github.com/hashilbasheer/argocd-test.git HEAD:main
