name: Patch YAML file
on:
  push:
    branches:
      - main     
env: 
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  CI_COMMIT_AUTHOR: Continuous Integration
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with deployment manifest
        uses: actions/checkout@v2
        with: 
          repository: hashilbasheer/argocd-test
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Clone remote repository
        run: git clone https://github.com/hashilbasheer/argocd-test.git remote
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Patch YAML file with yq
        run: |
          yq e ".spec.template.spec.containers[0].image = \" ghcr.io/hashilbasheer/react-poc:${IMAGE_TAG}\"" -i remote/deploy/deploy.yaml
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          repository: hashilbasheer/argocd-test
