name: Deploy to AKS using ArgoCD

on:
  push:
    branches:
      - main1

env:
  REPO: <YOUR_GITHUB_REPO>
  APP_NAME: react-app
  ARGOCD_SERVER: <YOUR_ARGOCD_SERVER>
  ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Install ArgoCD CLI
        run: |
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.1.1/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
      
      - name: Deploy to AKS using ArgoCD
        run: |
          argocd login $ARGOCD_SERVER --insecure --username admin --password $ARGOCD_TOKEN
          argocd app create $APP_NAME --repo $REPO --path ./deploy --dest-server https://kubernetes.default.svc --dest-namespace default
          argocd app sync $APP_NAME --wait
