name: ArgoCD Sync

on:
  push:
    branches:
      - main

env:
  APP_NAME: your-app-name
  NAMESPACE: your-namespace
  ARGOCD_SERVER: https://argocd-server-url.com
  ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  argocd-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install kubectl and argocd CLI
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.1.3/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Update values.yaml
        run: |
          sed -i 's/old-value/new-value/g' path/to/values.yaml
      
      - name: Sync with ArgoCD
        run: |
          argocd login --insecure --grpc-web --username admin --password $ARGOCD_TOKEN $ARGOCD_SERVER
          argocd app sync $APP_NAME -n $NAMESPACE

      - name: Update manifest in AKS cluster
        run: |
          kubectl config use-context $(kubectl config get-contexts -o name | grep aks-cluster-name)
          argocd app sync $APP_NAME -n $NAMESPACE --kubeconfig $KUBECONFIG
