name: Update ArgoCD image tag
on:
  push:
    branches:
      - main
env: 
  IMAGE_TAG: e7d2610      

jobs:
  update-argocd-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArgoCD repository
        uses: actions/checkout@v2
        with:
          repository: hashilbasheer/argocd-test
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GHCR_TOKEN }}
 

      - name: Change image tag
        run: |
          sed -i 's/image: .*$/image: ghcr.io/hashilbasheer/react-poc:{{ env.IMAGE_TAG }}/' ${{ github.workspace }}/deploy/deploy.yaml
        working-directory: ${{ github.workspace }}/deploy

      - name: Commit and push changes
        run: |
          git config --local user.email "hashilbasheer@gmail.com"
          git config --local user.name "hashilbasheer"
          git commit -am "Update image tag"
          git push origin HEAD
        working-directory: ${{ github.workspace }}/deploy
