name: Selenium Test - Check Application Status

on:
  workflow_dispatch:

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip firefox
          pip3 install selenium
      
      - name: Run Selenium script
        env:
          APP_URL: http://volvosalescockpit.6ed500daefb04e85a911.eastus.aksapp.io
        run: |
          python3 app_status.py
