name: Selenium Test

on:
   workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up Chrome driver
      run: |
        LATEST_RELEASE=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl https://chromedriver.storage.googleapis.com/$LATEST_RELEASE/chromedriver_linux64.zip --output chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        rm chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Run script
      run: |
        python my_selenium_test.py http://volvosalescockpit.6ed500daefb04e85a911.eastus.aksapp.io/
