name: Selenium Test - Check Application Status

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium
      
      - name: Run Selenium tests
        run: |
          python my_selenium_test.py
      
        env:
          APP_URL: http://volvosalescockpit.6ed500daefb04e85a911.eastus.aksapp.io
          CHROMEDRIVER_PATH: /usr/lib/chromium-browser/chromedriver
          CHROME_BIN: /usr/bin/chromium-browser
          
        continue-on-error: true
