name: Selenium Test

on:
   workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
             npm install
             npm install chromedriver

      - name: Run Chrome web driver tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          chromeDriver = new webdriver.Builder()
            .forBrowser('chrome')
            .setChromeOptions(new chrome.Options().headless())
            .build();
          npm run test:chrome
          
          
      - name: Check application URL
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://volvosalescockpit.6ed500daefb04e85a911.eastus.aksapp.io/)
          if [ $response -eq 200 ]
          then
              echo "Application URL is returning 200 status code"
          else
              echo "Application URL is not returning 200 status code"
              exit 1
          fi    

      - name: Clean up
        run: |
          chromeDriver.quit();
          # Add any other necessary cleanup steps here

