name: SONAR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:    

jobs:
  Sonar:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build app
          run: npm run build
        - name: Run tests
          run: npm run test
        - name: SonarCloud scan
          uses: SonarSource/sonarcloud-github-action@master
          with:
            args: 
              -Dsonar.organization=hashilbasheer
              -Dsonar.projectKey=poc-sonar-key
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.login=$SONAR_TOKEN
