name: SONAR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:    

jobs:
  Sonar:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build app
          run: npm run build
        - name: Run tests
          run: npm run test
        - name: Cache SonarCloud packages
          uses: actions/cache@v1
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
        - name: Sonar Analysis
          run: sonar-scanner --non-interactive -Dsonar.projectKey=poc-sonar-key -Dsonar.organization=react-poc-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
