name: SONAR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:    

jobs:
  Sonar:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build app
          run: npm run build
        - name: Run tests
          run: npm run test
        - name: Install Sonar Scanner
          run: |
            curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d /opt
            export PATH="$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin"
            
        - name: Run Sonar Scan
          run: sonar-scanner --non-interactive -Dsonar.projectKey=poc-sonar-key -Dsonar.organization=react-poc-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
